MeVisLab/pythonqt

src/PythonQt.cpp
Py_Finalize crash is caused by references mishandling in Enums. This PR fixes the issue.
=> Fix crash in GC: PyTuple_SET_ITEM steals reference

src/PythonQtObjectPtr.cpp, src/PythonQtQFileImporter.h, src/PythonQtThreadSupport.h
This prevents `file not found with <angled> include; use "quotes" instead` errors.
=> Use `quote` characters around includes of PythonQt headers.

build/python.prf
With Python 3.8, python3-config --libs doesn't contain the python link target.
To avoid link issues, we first test if the python config utility accepts the
'--embed' parameter and use the output when possible.
Fixes: #6
=> Fix build with Python 3.8

build/python.prf, src/PythonQt.cpp, src/PythonQt.h, src/PythonQtImporter.cpp, src/PythonQtInstanceWrapper.cpp, src/PythonQtSignalReceiver.cpp
Tested with Python-3.8.5 debug build and memcheck, does not fix all leaks but some, reduces dynamic memory leaks by 2/3rds
=> Fix reference/memory leaks

src/gui/PythonQtScriptingConsole.h
In GUI ScriptingConsole, fix so that history position is correct after call to setHistory so that pressing up-arrow works and shows last history item.
=> Fix history position in call to ScriptingConsole setHistory

src/PythonQtStdIn.cpp, src/PythonQtStdIn.h
pip and some other Python modules use this attribute to check if they are running in an interactive console.
Co-authored-by: Fernando Perez-Garcia <fernando.perezgarcia.17@ucl.ac.uk>
fixes #48
=> Add isatty() method to PythonQtStdIn class

.github/workflows/Dockerfile_gcc, .github/workflows/build.yml
This is a first attempt to setup some CI builds, currently only building PythonQt using qmake/make using gcc 7, 9 and 11.
This just uses the GCC docker images and the Python and Qt images that are installed there (Python 3.7.3 / Qt 5.11.3 for gcc 7 and 9, Python 3.9.2 / Qt 5.15.2 for gcc 11).
Probable tasks for future PRs:
- setup Windows and Mac builds
- use specific Qt and Python version combinations
- run the created generator for a specific Qt version and provide the created code
- a bit unrelated - switch to CMake (there are already several forks who have done this)
I also tried to use gcc 5 and 6, but if just using the standard GCC docker images with the standard Python and Qt packages, they run with Python 3.4 and Qt 5.3.2, which is not supported with the current version (does not …
=> Set up CI builds for different gcc versions

.github/workflows/build.yml, .github/workflows/dockerfiles/Dockerfile_centos7, .github/workflows/dockerfiles/Dockerfile_gcc11, .github/workflows/dockerfiles/Dockerfile_gcc7
- uses gcc 4.8.5, Python 3.6.8 and Qt 5.9.7
- also remove gcc 9 build (keep gcc 7 and 11)
=> Add CentOS7 docker image to CI

build/common.prf
- trying with -std=c++98 failed with a lot of various errors
- shall ensure that only C++11-compatible changes are merged for now
=> Add -std=c++11 flag to check for problems

src/PythonQt.cpp, src/PythonQt.h, src/PythonQtImporter.cpp, src/PythonQtInstanceWrapper.cpp, src/PythonQtSignalReceiver.cpp
As [proposed by @florianlink](https://github.com/MeVisLab/pythonqt/pull/79#issuecomment-1367462519), this will revert the ref count fixes as long as the crashes they cause are not understood.
(taken from [revert-refcount-fixes](https://github.com/MeVisLab/pythonqt/tree/revert-refcount-fixes) branch created by @usiems).
=> Revert refcount fixes

src/PythonQt.cpp
This change avoids a warning message "__package__ != __spec__.parent" (in Python 3.9) on relative imports from modules which have the import paths set with PythonQt::self()->setModuleImportPath(). Since __spec__ is meant to replicate some settings like __path__, this seems the correct solution.
=> Update __spec__ too (if existing) when setting the import path

.github/workflows/build.yml, src/PythonQt.cpp, src/PythonQtClassWrapper.h, src/PythonQtInstanceWrapper.h, src/PythonQtSignalReceiver.cpp
Python 3.11 removed some fields in the PyCodeObject, [but introduced access functions](https://docs.python.org/3/c-api/code.html#c.PyCode_GetVarnames). Thus, the similarly named function is enough to fix the build issue.
=> Fix build with Python 3.11

.github/workflows/build.yml, build/PythonQt.prf, build/common.prf, build/python.prf, extensions/PythonQt_QtAll/PythonQt_QtAll.pro, generator/generator.h, generator/generator.pri, generator/shellheadergenerator.cpp, generator/shellimplgenerator.cpp, src/src.pri, src/src.pro, tests/tests.pro
* Initial CI for Windows via GHA with `make check` to run unit-tests
* Basic `clang-msvc` support
* Fixes for `msvc` and `mingw`
* Support for LTO (`CONFIG+=ltcg`) builds on all platforms
* Minor code improvements, including build scripts unification
=> CI for Windows

src/PythonQtSignalReceiver.h
(when multi-threading is enabled)
It seems this is done with a slot call, which gives up the GIL, but the GIL is needed in the destructor of the PythonQtSignalReceiver when a callable target was given. Fix this by simply using a PythonQtSafeObjectPtr for the _callable.
=> Fix crash when using QObject::disconnect method

.github/workflows/build.yml
1. macOS 10.15 was removed from GHA long ago.
https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
2. Python 2.7 is obsolete, thus removed for Windows and macOS, but still in CentOS7
3. RockyLinux9 is here for CI from now on
=> CI runners clean-up 

src/PythonQtPythonInclude.h
- this has been introduced in #89 and breaks builds including *PythonQt.h*
The reverted code undefines `_POSIX_THREADS` (and a couple of other defines), which are queried in *PythonQt.h*.
If it is not set on a POSIX system, we get the error:
```Require native threads. See https://bugs.python.org/issue31370```
As far as I can see, none of these defines comes from *python.h*, at least not in current versions of Python.
=> Revert undefining some defines

src/PythonQtPythonInclude.h
- only undefining _POSIX_THREADS had be a problem
- see #103
=> Add back undefining _POSIX_C_SOURCE and _XOPEN_SOURCE

build/common.prf, generator/generator.pri, generator/parser/compiler_utils.h, src/src.pri, tests/tests.pro
This is a minimalist set to pass the build tests (though I don't know about the 'nmake not found' failure).  It just fixes the multiple definitions of the compiler standard and the QStringList typedef problem.
=> Qt6: initial changes to make compilation work

generator/parser/codemodel_pointer.h
This function was deprecated in Qt 5.14 then removed in Qt6, along with 'store()'.  The deprecated function information in Qt 5.15LTS says to use 'loadRelaxed', most likely on the basis that 'load' didn't guarantee better memory ordering that relaxed provides (see the standard c++ explanations of std::memory_order_relaxed etc).
=> Replace deprecated QAtomicPointer<T>::load()

generator/generator.cpp
The suggested replacements are std::stable_sort and std::sort which work (compile) in both Qt5 (5.15LTS) and Qt6.
=> Qt6: qSort and qStableSort removed

generator/abstractmetabuilder.cpp, generator/abstractmetalang.cpp, generator/prigenerator.cpp, generator/setupgenerator.cpp, generator/shellgenerator.cpp, generator/shellheadergenerator.cpp, generator/shellimplgenerator.cpp
This completes the qSort handling in generator/ including related changes caused by the removal of QSet<>::toList() and QSet<>::fromList() in Qt6 (obsoleted in Qt5.14).
=> Qt6: qSort, toList and fromList removal

generator/main.cpp, generator/setupgenerator.cpp, generator/typesystem.h
The new declaration is in 5.14 and the old is removed in 6, the patch provides forward compatibility with older versions of Qt.
=> Qt6: QString::SkipEmptyParts moved to Qt

generator/abstractmetabuilder.cpp, generator/asttoxml.cpp, generator/typesystem.h
This provides compatibility with the removal of the global ::endl for use with QTextStream; Qt6 requires Qt::endl.
It also includes Qt6 specific changes necessary to deal with the replacement of QTextCodec by QStringConverter and the slight changes to the default setup of QTextStream (to UTF-8 with auto-detect of UTF-16).
=> Qt6: QTextStream compatibility

generator/parser/declarator_compiler.cpp, generator/parser/name_compiler.cpp, generator/parser/parser.cpp
The warnings are already only emitted with GCC so changing them to the GCC diagnostic pragma is safe.
=> Eliminate warnings about #warning

generator/generator.pri, generator/typesystem.cpp
This works around the need to rewrite the XML parser in generator/typesystem.cpp by invoking the Qt5 compatibility library; this is the only thing in the generator which requires it but the alternative is a complete rewrite of the XML reading code.
=> Qt6: generator/typesystem.cpp: XML workround

generator/abstractmetabuilder.cpp, generator/abstractmetalang.cpp, generator/abstractmetalang.h
These changes use the new and existing support inside the parser to handle constexpr in Qt6 files and to ignore (with a warning) 'auto' functions.
=> Handle constexpr, auto

generator/setupgenerator.cpp, generator/shellgenerator.cpp, src/PythonQtMethodInfo.cpp
Also add the alternate types that are available in Qt5 to replace the types deprecated in Qt5.14 (allows Qt5.15LTS users to make changes for compatibility with Qt6.)
=> Qt6: fixes for removal of Qt5 types

build/common.prf, generator/qtscript_masterinclude.h
The fix for Qt5.12 breaks pythonqt_generator for 5.11.  Patch includes better checking for precompiled headers and errors out early rather than failing when linking the src/ with mysterious missing symbols.
=> Fix problems in Qt5.11 generator

generator/parser/codemodel.cpp, generator/parser/codemodel.h, generator/parser/rpp/pp-engine-bits.h, generator/parser/rpp/pp-environment.h, generator/parser/rpp/pp-macro-expander.h, generator/parser/rpp/pp-macro.h, generator/parser/rpp/preprocessor.cpp
Corresponding warnings are already turned off on clang in generator/generator.pri.  There's no G++ command-line option to turn them off without explicitly disabling other warnings (-Wpedantic).
=> Eliminate warnings about anonymous structs on GCC

generator/main.cpp
This ensures that printf() in the generator does not get file buffered (and therefore delayed relative to stderr) when piping output to a file and provides ReportHandler "context" for ReportHandler warnings.
=> generator: improve error handling

generator/abstractmetabuilder.cpp, generator/abstractmetalang.cpp, generator/abstractmetalang.h, generator/generator.cpp, generator/setupgenerator.cpp
In some places the list was sorted by pointer (resulting in a random sort) in other cases by name, sometimes with stable_sort, sometimes not. Now sort by name and use a stable_sort.
=> generator: AbstractMetaClassList: correct sorting

generator/parser/parser.cpp, generator/typesystem_core.xml, generator/typesystem_gui.xml, generator/typesystem_network.xml, generator/typesystem_qml.xml
Support for parsing enum class declarations (from c++ 11)
=> Enum class support

generator/typesystem_core.xml
const_iterators and other iterators became visible to the generator with changes in Qt5.14.  This removes the corresponding iterators from the affected classes.
=> generator: fix iterator issues with Qt5.14 headers

.gitignore, generator/main.cpp, generator/parser/ast.cpp, generator/parser/binder.cpp, generator/parser/control.cpp, generator/parser/control.h, generator/parser/lexer.h, generator/parser/parser.cpp, generator/parser/parser.h
Add some code that helps with debugging the problems that the generator has with newer Qt versions:
- command line option for printing parser errors
- keep track of the current (approximate) source code location, and make current token readable in debugger (only in Debug mode)
=> Improve debugging

.github/workflows/build.yml, generator/parser/tokens.cpp
- Add sanitizers to the PythonQt testing step and the generator step. Due to the large number of leaks, leak_detects is temporarily disabled.
- Add consistency check between TOKEN_KIND enum and _S_token_names array, because otherwise CI fails with the ASan error "Array index out of bounds".
=> Improve CI with sanitizers

generator/abstractmetabuilder.cpp
This fixes explicit new/delete, storage leaks (missing delete) and iteration over a QHash while modifying it (deleting specific keys in an iterator).
Tested against the current make_generator_work_for_5.15 branch; it generates identical output and crashes in the same places (6.5.3).
=> Fix: AbstractMetaBuilder::classesTopologicalSorted

generator/abstractmetabuilder.cpp, generator/abstractmetabuilder.h
A step towards #138.
Generator behaviour doesn't change (for example, based on wrappers generated for qt 5.12 before and after this fix), but the amount of leaked memory decreases by a third (from 57 to 37 MB). The measurements were carried out on the make_generator_work_for_5.15 branch.
I will try to continue to reduce the number of leaks in the near future.
=> Reduce memory leaks

generator/generatorsetqtscript.cpp, generator/generatorsetqtscript.h, generator/prigenerator.cpp, generator/prigenerator.h, generator/setupgenerator.cpp, generator/setupgenerator.h, generator/shellgenerator.h
This introduces the --max-classes-per-file command line argument. The default for this is 30, as before.
The motivation for this is that comparing the output for different versions (of Qt or the generator) gets easier when everything is one file, so that added or removed classes don't change the output of subsequent files. For this purpose one can use `--max-classes-per-file=10000`.
=> Make number of classes per generated file configurable

.github/workflows/build.yml, .github/workflows/build_latest.yml
CI workflow for Qt5 latest builds on Ubuntu-latest worker based on #149.
Adds a new step that allows to build PythonQt with freshly generated code.
Now contains qt 5.12 version for testing a new scenario, but easily can be changed to 5.* (equivalent to 5.15) when PR #146 is merged.
=> Qt5 latest workflow

generator/main.cpp, generator/main.h, generator/typesystem.cpp, generator/typesystem.h, generator/typesystem_core.xml, generator/typesystem_gui.xml
The attributes after-version and before-version restrict the validity of any element to certain Qt versions (after-version means actually including the given version). Additionally there is a new "group" element that only serves the purpose of grouping elements so that the version range doesn't need to repeated. Version strings can be something like "6", "6.5", or "6.5.1".
Some actual elements from the typesystem files have been equipped with these new version attributes for testing purposes.
=> Add version qualifiers to typesystem XML files

.github/workflows/build.yml
where the Qt version can't be determined automatically, probably because the include files are inside of frameworks, but that's ok, so we also test giving the version on the command line.
Obviously the merge of the previous merge request was somewhat premature... :)
=> Fix workflow for MacOS

.github/dependabot.yml
To automatically update sub-actions like `checkout` or `aqtinstall`, etc.
It is very useful for maintenance to get updates for actions automatically, this happens very rare.
The first proposed PR with `checkout@v4` will break the CI on Centos7. But this issue should be resolved by reverting manually the single line of code just in the branch of PR. Later Dependabot will try again to send the update for this line, but after closing the PR with `@dependabot close` no more annoying attempts to update from `checkout@v3` to `checkout@v4` in any `*.yml` are expected, until the next version `v5` is out.
=> Add Dependabot for GH actions

extensions/PythonQt_QtAll/PythonQt_QtAll.pro, generator/abstractmetabuilder.cpp, generator/abstractmetabuilder.h, generator/abstractmetalang.cpp, generator/abstractmetalang.h, generator/generator.pri, generator/typesystem.cpp, generator/typesystem.h, src/PythonQt.cpp, src/PythonQtConversion.cpp, src/PythonQtConversion.h, src/src.pro
QStringView and QAnyStringView are interfaces to treat different string origins the same. In Qt5 we had QStringRef instead.
To support this as an argument from Python, we also need to (temporarily) store the original QString somewhere, and then create the Q(Any)StringView from it. The old code supported QStringRef as return value, but didn't allow it as argument type, as far as I can see. But the code supports QString* as argument type, which is a somewhat similar case. I took my inspiration how to handle the view classes from that.
After fixing this it became apparent that in C++ there often were several overloads of a method that amounted to basically the same call interface in Python (QString, QLatin1String, QStringView). So I wrote code to remove superfluous overloads.
This is …
=> Support QStringView and QAnyStringView as argument and return type

src/PythonQtClassInfo.cpp, src/PythonQtClassInfo.h
Enum class values seem to have pretty generic names (as there is no danger
of name clashes in C++, as they must always be prefixed with the enum
class name). So add them to the enum type in Python too, so one can
always write something like QActionGroup.ExclusionPolicy.None instead of
QActionGroup.None.
Ideally we wouldn't add the enum values to the parent class at all, but
I don't want to break compatibility with older versions of PythonQt.
Also added code to escape names that are reserved in Python.
=> Add "enum class" values to the enum type in Python

.github/workflows/build.yml, .github/workflows/build_latest.yml
- also remove INCLUDE env var which with MSVC points to some 
include directories which the parser cannot handle
=> Add Windows CI to compile generated sources

generator/typesystem_core.xml, generator/typesystem_gui.xml, generator/typesystem_multimedia.xml, generator/typesystem_network.xml, generator/typesystem_qml.xml, generator/typesystem_quick.xml, generator/typesystem_webenginewidgets.xml, generator/typesystem_xml.xml
Just so that there are no unknown rejected classes and enums in the log file for Qt 6.6. The support for some of the new classes might be incomplete.
One notable addition is the Cbor support in Qt. I got a little bit creative with the supporting classes like QCborTag (which is just a qint64 in Python now), and QCborNegativeInteger (which is simply not supported). Also the string reading methods of QCborStreamReader were modified, because PythonQt can't currently support arbitrary templated parameter/return types. If somebody wants to provide a patch to make it match the C++ interface...
I also re-allowed some methods in QtNetwork which might break compilation if Qt is compiled without SSL support. If this is a problem, please add a comment.
=> More typesystem entries (added classes and rejections)

generator/parser/rpp/pp-qt-configuration
(appeared in QMessageBox in Qt 6.6.2)
=> Ignore static_assert in header files

generator/typesystem.cpp
(QPair is more or less deprecated)
=> Also register std::pair with the generator

generator/typesystem_sql.xml
=> Replace deprecated include qsql.h with qtsqlglobal.h for Qt 6

generator/main.cpp
Hi,
This PR fix, on Arch, with GCC 13.2.1:
```cpp
make[1]: Entering directory '/home/nim/aur/pythonqt/src/pythonqt-3.5.0/generator'
g++ -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wno-deprecated-declarations -pedantic -Winit-self -Wuninitialized -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DRXX_ALLOCATOR_INIT_0 -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -I. …
```
=> fix format-security

src/PythonQt.cpp, src/src.pri
+ small fix for rare problem, but this reference management pattern is safer and preferable
=> Force C++11 for older Qt versions with obsolete compilers (f.e. GCC 4.9.2)

.github/workflows/build.yml, .github/workflows/build_latest.yml
and other nice options like PYTHONMALLOC=debug_malloc (useful for ASan) and more rigorous warnings handling
Thanks to these features, I've caught some memory handling problems in my project. Thus, let's consider it to be a good practice, that will be extremely useful for memory management clean-up of the PythonQt runtime.
=> Add PYTHONDEVMODE to improve tests

generator/typesystem_core.xml
This class (QOperatingSystemVersionUnexported) must be generated to provide the proper inheritance of methods.
=> 6.6.3 introduced a new helper class for QOperatingSystemVersion

generator/main.cpp, generator/typesystem.cpp
Hi,
This is the following #197, except it is on macos with clang 16.0.6:
```
main.cpp:99:18: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
qWarning((reason + "Assuming standard binary install using frameworks.").toUtf8().constData());
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.cpp:99:18: note: treat the string as an argument to avoid this
qWarning((reason + "Assuming standard binary install using frameworks.").toUtf8().constData());
^
"%s",
=> fix format-security on Q_OS_MAC

generator/typesystem_quick.xml
Otherwise one can't switch the desired render API for the QtQuick framework.
(We need this in the MeVisLab context.)
=> Allow to set and get the render API in QQuickWindow

generator/generatorsetqtscript.cpp, generator/typeparser.cpp, generator/typesystem.cpp, src/PythonQtClassInfo.cpp, src/PythonQtMethodInfo.cpp, tests/PythonQtTests.cpp, tests/tests.pro
* Main change: `CHAR_MIN` is `0` for unsigned `char`. In general, the "sign-ness" of the `char` type is implementation-specific. There is a proper check in the type conversion facility, but the test-case supposes the `char` to be signed, that is wrong.
* `opengl` is not required for tests (fix build without `opengl` module)
* Fix build with PYTHONQT_DEBUG enabled
* Small fixes to build with less warnings.
=> Fix small issues in build and tests.

generator/typesystem_gui.xml
but I don't know why, since the method should simply work (like the other find variant). And it was reported that the method was previously (before Qt6) created, even though it should have been suppressed.
=> QPixmapCache::find(QString, QPixmap*) was suppressed

.github/workflows/build_latest.yml
New environment variable `QT_ROOT_DIR` should be used instead of `Qt5_Dir`/`Qt6_Dir`.
Also, `PATH` is now correctly updated by install-qt-action, thus no workaround setting `GITHUB_PATH` is required. 
See https://github.com/jurplel/install-qt-action/blob/v4/README_upgrade_guide.md
=> Update install-qt-action to v4

.github/workflows/build.yml
Migrate to `QT_ROOT_DIR`, remove obsolete `PATH` handling
Closes #220
=> Update install-qt-action for Win and Mac builds

.github/workflows/build.yml
1. [CentOS7 reached EOL](https://www.redhat.com/en/topics/linux/centos-linux-eol) and GHA support for the corresponding [container was abandoned](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/). However, `node20` requires at least `glibc2.27`, which is not available in CentOS, but upgrading the glibc version contradicts the meaning of using older CentOS. The proposed solution in this PR is to use corresponding environment variable, that helps to extend CentOS CI availability for some time. Also,  `mirrorlist.centos.org` was turned off, so switch [to vault](https://serverfault.com/questions/904304/could-not-resolve-host-mirrorlist-centos-org-centos-7) is required (see `sed` for configs in PR)
2. [macOS-11 runner is no …
=> Fix macOS and CentOS CI

.github/workflows/build.yml, src/PythonQt.cpp, tests/PythonQtTestMain.cpp, tests/PythonQtTests.cpp, tests/PythonQtTests.h
1. [PyUnicode_FromString](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_FromString) returns a new reference, thus memory leak took place and is fixed.
2. To diagnose such leaks, basic memory tests are implemented, that to be extended later. To run these memory tests the  `PYTHONQT_RUN_ONLY_MEMORY_TESTS` environment variable should be used. 
3. These tiny specialized memory tests are temporary useful until memleaks are fixed in `PythonQt::cleanup` for general main tests.
4. So, this PR adds a CI step to run mentioned memory tests with Leak Sanitizer turned on via  `ASAN_OPTIONS=detect_leaks=1`.
=> Fix memory leak and add memory tests

.github/workflows/build.yml, .github/workflows/build_latest.yml
When submitting a PR, it's important to ensure that the project builds correctly. However, the `Ubuntu` build takes quite a [long time](https://github.com/MeVisLab/pythonqt/actions/runs/10405564335/usage). To speed up the build, add a [ccache action](https://github.com/hendrikmuhs/ccache-action) to the CI pipeline.
=> Add ccache to CI

src/PythonQtInstanceWrapper.cpp
`PyBaseObject_Type.tp_getattro` uses `PyObject_GenericGetAttr`, which returns a [new reference](https://docs.python.org/3/c-api/object.html#c.PyObject_GenericGetAttr) that is lost when using PyDict_Copy.
=> Fix memory leak with PyDict_Copy

README.md
Add more detailed build instructions to the Readme to avoid some common pitfalls (see #230) when building PythonQt.
For now I left the original build section in the Readme, but in my opinion the instructions can be removed.
Currently I mention of the env-vars I used for building it with conan, maybe some are not necessary in all configurations.
=> Add detailed build instructions to Readme

generator/abstractmetabuilder.cpp, generator/shellgenerator.cpp, generator/shellheadergenerator.cpp, generator/shellimplgenerator.cpp, generator/typesystem_core.xml, generator/typesystem_gui.xml
This fixes the problem introduced with Qt 6.7.3, that the wrapper for the "Qt" namespace suddenly got methods like
` QKeyCombination  static_Qt_operator+(Qt::KeyboardModifiers  modifiers, Qt::Key  key);`
The problem is two-fold:
1. No proper name-mangling was applied to these static methods ("operator+" should be replaced by "\_\_add\_\_").
2. Static operators don't work in PythonQt anyway and shouldn't be generated (we also can't assign the operator to the first argument type, since that is only a enum type, which has no separate wrapper generated).
The trigger for these problems was that these static operators have been moved to the Qt namespace in version 6.7.3.
=> Fix Qt 6.7.3

generator/typesystem_webenginewidgets.xml
albeit without the callback parameter so far
=> reintroduce the runJavaScript method on QWebEnginePage for Qt 6

.github/workflows/build.yml, src/PythonQt.cpp
Fix build with Python 3.13 see https://github.com/MeVisLab/pythonqt/issues/245
=> Fix build with Python 3.13

.github/workflows/build.yml
- see https://github.com/actions/runner/issues/2906
Node16 support has been completely removed from GH actions, together with CentOS 7 support, and the workaround no longer works.
There are more hacky workarounds to get it running again, but I'm reluctant to use them. Any installation on these systems should be fine using a released version - further changes in PythonQt will be most likely be related to Qt 6 only.
CC @he-hesce.
=> Remove no longer supported CentOS 7 builds

src/PythonQt.cpp
if they were implicitly added first (to PythonQt.private), and the explicit register method isn't given a Python module object, only a name.
Fixes #260
Class QObject is implicitly registered first because PythonQt registers two interface objects that are derived from QObject.
=> Fix that registered classes are not added to the designated package

generator/parser/name_compiler.cpp
PythonQt/generator/parser/name_compiler.cpp:111:46: \
warning: 'count' is deprecated: Use size() or length() instead.
[-Wdeprecated-declarations]
=> COMP: Remove use of deprecated 'count()' function

src/PythonQtClassInfo.cpp, src/PythonQtConversion.cpp, src/PythonQtConversion.h, src/PythonQtInstanceWrapper.cpp, src/PythonQtMethodInfo.cpp, src/PythonQtSlot.cpp, src/PythonQtUtils.h
This changes deprecated Qt6 paradigms to either backward-compatible ones or uses preprocessor conditionals for Qt5 and Qt6 differences. This ensures compatibility with both Qt versions.
---
This pull request supersedes https://github.com/MeVisLab/pythonqt/pull/270
=> chore: Remove deprecated Qt5 paradigms

generator/shellheadergenerator.cpp
To avoid the collision, use Q_SLOTS instead
=> NumPy 2 defines its own "slots". 

src/PythonQtStdDecorators.h
Starting with Qt 5.15, the `qrand` function has been deprecated in favor of `QRandomGenerator`. This change updates `PythonQtStdDecorators.h` to use `QRandomGenerator` when building against Qt 5.15 or later.
See qt/qtbase@b3c0e9afa ("Deprecate qrand/qsrand", 2001-09-17)
---
> [!NOTE]
> For reference, those patches were developed in the context of the `commontk/PythonQt` fork.
> 
> Cherry picked from commits commontk/PythonQt@c1579e2
=> Fix warning related to use of qrand() when building against Qt 5.15

src/PythonQtClassInfo.cpp, src/PythonQtClassWrapper.cpp
Starting with Qt 5.15, the conversion functions between QList and QSet (e.g., `QSet::fromList`) have been deprecated in favor of range constructors.
This change updates the code to use the new range constructors to avoid deprecation warnings starting from Qt 5.14 (instead of Qt 6)
Related upstream Qt commits:
* qt/qtbase@92f984273 ("Deprecate conversion functions between QList and QSet", 2019-05-07)
* qt/qtbase@e59e5643b ("Use QT_DEPRECATED_X instead of Q_DECL_DEPRECATED_X", 2020-02-25)
---
> [!NOTE]
> For reference, those patches were developed in the context of the `commontk/PythonQt` fork.
> 
> Cherry picked from commits commontk/PythonQt@630e37667
=> fix: Address warnings with QSet::fromList in Qt 5.15

src/PythonQtSlot.cpp
Follow-up of c00ebf4d ("Replace NULL with nullptr", 2023-01-01)
---
> [!NOTE]
> For reference, those patches were developed in the context of the `commontk/PythonQt` fork.
> 
> Cherry picked from commits commontk/PythonQt@5d2c9b6f1
=> Replace NULL with nullptr

.github/workflows/build.yml, generator/main.cpp, generator/simplecpp/README.txt, generator/simplecpp/simplecpp.cpp, generator/simplecpp/simplecpp.h
This PR modernizes how the generator discovers Qt headers/frameworks and vendors a newer `simplecpp` with framework-aware search logic. Together these changes make builds robust on macOS (Qt frameworks) and cleaner across all platforms.
* Bumps `generator/simplecpp/{simplecpp.h, simplecpp.cpp}` to **patched-2025-08-30-37fa4f49b** (upstream: commontk/simplecpp@bfc53ad; previously danmar/simplecpp@37fa4f4).
* Re-applies local patch: `generator/simplecpp/do_not_stop_on_error.patch`.
* Introduces a typed, ordered search path API:
* `DUI::PathKind { Include, SystemInclude, Framework, SystemFramework }`
* `DUI::searchPaths` plus helpers `addIncludePath`, `addSystemIncludePath`, `addFrameworkPath`, `addSystemFrameworkPath`
* Back-compat: if `searchPaths` is empty, legacy `includePaths` is …
=> Qt header discovery & framework support; vendor simplecpp update

src/PythonQt.cpp, src/PythonQt.h, src/PythonQtBoolResult.cpp, src/PythonQtClassWrapper.cpp, src/PythonQtConversion.cpp, src/PythonQtImporter.cpp, src/PythonQtInstanceWrapper.cpp, src/PythonQtSignal.cpp, src/PythonQtSlot.cpp, src/PythonQtStdOut.cpp, src/PythonQtUtils.h
This pull request removes obsolete compatibility code for Python 2 and outdated 
preprocessor conditionals for Python versions < 2.4.
* Remove all `#ifndef PY3K` conditionals and related branches, consolidating on Python 3 APIs. This drops redundant code paths and consistently renames `nb_nonzero` helpers to `nb_bool`.
* Remove the comment related to the use of `Py_FlushLine` in `custom_system_exit_exception_handle` in `PythonQt.cpp`, which is not needed in Python 3.x. See python/cpython@79139b247b0 ("Kill off softspace completely (except in formatter.py which seems to have a different feature with the same name). The change to test_doctest.txt reduces the doctest failures to 3.", 2007-02-09)
* Remove outdated `PY_VERSION_HEX` conditional branches.
=> chore: Remove obsolete Python 2 compatibility code

examples/PyLauncher/main.cpp, generator/abstractmetabuilder.cpp, generator/abstractmetalang.cpp, generator/abstractmetalang.h, generator/generator.cpp, generator/parser/binder.cpp, generator/parser/codemodel.cpp, generator/prigenerator.cpp, generator/setupgenerator.cpp, generator/shellimplgenerator.cpp, generator/typesystem.cpp, generator/typesystem.h, src/PythonQt.cpp, src/PythonQtClassInfo.cpp, src/PythonQtClassWrapper.cpp, src/PythonQtConversion.cpp, src/PythonQtConversion.h, src/PythonQtImporter.cpp, src/PythonQtInstanceWrapper.cpp, src/PythonQtMethodInfo.cpp, src/gui/PythonQtScriptingConsole.cpp, tests/PythonQtTests.cpp
This pull request includes two main changes:
1. Replaces deprecated `foreach` and `Q_FOREACH` macros with C++11 range-based for loops as recommended by Qt 5.7+.
2. Improves const correctness by using `const` references in range-based for loops and other relevant places.
=> chore: Replace deprecated Qt macros and Improve const correctness

src/PythonQtImporter.cpp
Python 3.12 deprecates direct use of global flags (`Py_VerboseFlag`, `Py_OptimizeFlag`). Query `sys.flags.verbose` / `sys.flags.optimize` at runtime (via a small helper) when building against 3.12+, and fallback to the legacy globals on older versions.
No functional change intended.
=> chore(importer): read `sys.flags` (verbose/optimize) on Python >= 3.12; fallback to legacy globals

src/PythonQt.cpp, src/PythonQtConversion.cpp, src/PythonQtConversion.h, src/PythonQtPythonInclude.h
This PR replaces remaining `PyInt_*` usages with the Python 3 `PyLong_*` equivalents.
=> chore: Migrate integer API usage from `PyInt_*` to `PyLong_*` (Python 3)

.github/workflows/build.yml, .github/workflows/build_latest.yml, .github/workflows/builddocs.yml, src/PythonQtDoc.h
- the branch itself has already been renamed, this only adapts the workflows
- see #144
Closes #144.
=> Rename master to main
